# Generated by Django 3.1.2 on 2021-01-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_description',
            field=models.CharField(default='', max_length=2000, verbose_name='Put the description'),
        ),
    ]
